repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [ --unsafe ]
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
      - id: mypy
        exclude: tests/
        additional_dependencies:
          - types-click
