[tool.poetry]
name = "latent_trainer"
version = "0.1.0"
description = "Latent trainer"
authors = ["Kaszanas <andrzej.bialecki94@gmail.com>"]
license = "All Rights Reserved"
readme = "README.md"
packages = [{include = "src/latent_trainer"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
click = "^8.1.3"
sc2-datasets = "^1.0.2"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.4.1"
flake8 = "^6.0.0"
isort = "^5.12.0"


[tool.poetry.group.doc.dependencies]
mkdocs = "^1.4.3"
mkdocs-include-markdown-plugin = "^4.0.4"
mkdocs-material = "^9.1.17"
mkdocstrings = "^0.22.0"
mkdocs-material-extensions = "^1.1.1"
mkdocs-autorefs = "^0.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
